// Generated by gencpp from file ros2_2/xxx.msg
// DO NOT EDIT!


#ifndef ROS2_2_MESSAGE_XXX_H
#define ROS2_2_MESSAGE_XXX_H

#include <ros/service_traits.h>


#include <ros2_2/xxxRequest.h>
#include <ros2_2/xxxResponse.h>


namespace ros2_2
{

struct xxx
{

typedef xxxRequest Request;
typedef xxxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct xxx
} // namespace ros2_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros2_2::xxx > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::ros2_2::xxx&) { return value(); }
};

template<>
struct DataType< ::ros2_2::xxx > {
  static const char* value()
  {
    return "ros2_2/xxx";
  }

  static const char* value(const ::ros2_2::xxx&) { return value(); }
};


// service_traits::MD5Sum< ::ros2_2::xxxRequest> should match
// service_traits::MD5Sum< ::ros2_2::xxx >
template<>
struct MD5Sum< ::ros2_2::xxxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros2_2::xxx >::value();
  }
  static const char* value(const ::ros2_2::xxxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros2_2::xxxRequest> should match
// service_traits::DataType< ::ros2_2::xxx >
template<>
struct DataType< ::ros2_2::xxxRequest>
{
  static const char* value()
  {
    return DataType< ::ros2_2::xxx >::value();
  }
  static const char* value(const ::ros2_2::xxxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros2_2::xxxResponse> should match
// service_traits::MD5Sum< ::ros2_2::xxx >
template<>
struct MD5Sum< ::ros2_2::xxxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros2_2::xxx >::value();
  }
  static const char* value(const ::ros2_2::xxxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros2_2::xxxResponse> should match
// service_traits::DataType< ::ros2_2::xxx >
template<>
struct DataType< ::ros2_2::xxxResponse>
{
  static const char* value()
  {
    return DataType< ::ros2_2::xxx >::value();
  }
  static const char* value(const ::ros2_2::xxxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS2_2_MESSAGE_XXX_H
