// Generated by gencpp from file ros2_2/xxxResponse.msg
// DO NOT EDIT!


#ifndef ROS2_2_MESSAGE_XXXRESPONSE_H
#define ROS2_2_MESSAGE_XXXRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros2_2
{
template <class ContainerAllocator>
struct xxxResponse_
{
  typedef xxxResponse_<ContainerAllocator> Type;

  xxxResponse_()
    : sum(0)  {
    }
  xxxResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::ros2_2::xxxResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros2_2::xxxResponse_<ContainerAllocator> const> ConstPtr;

}; // struct xxxResponse_

typedef ::ros2_2::xxxResponse_<std::allocator<void> > xxxResponse;

typedef boost::shared_ptr< ::ros2_2::xxxResponse > xxxResponsePtr;
typedef boost::shared_ptr< ::ros2_2::xxxResponse const> xxxResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros2_2::xxxResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros2_2::xxxResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros2_2::xxxResponse_<ContainerAllocator1> & lhs, const ::ros2_2::xxxResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros2_2::xxxResponse_<ContainerAllocator1> & lhs, const ::ros2_2::xxxResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros2_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros2_2::xxxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros2_2::xxxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros2_2::xxxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros2_2::xxxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros2_2::xxxResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros2_2::xxxResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros2_2::xxxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::ros2_2::xxxResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::ros2_2::xxxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros2_2/xxxResponse";
  }

  static const char* value(const ::ros2_2::xxxResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros2_2::xxxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 服务器响应发送的数据\n"
"int32 sum\n"
;
  }

  static const char* value(const ::ros2_2::xxxResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros2_2::xxxResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xxxResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros2_2::xxxResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros2_2::xxxResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS2_2_MESSAGE_XXXRESPONSE_H
