// Generated by gencpp from file ros2_2/xxxRequest.msg
// DO NOT EDIT!


#ifndef ROS2_2_MESSAGE_XXXREQUEST_H
#define ROS2_2_MESSAGE_XXXREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros2_2
{
template <class ContainerAllocator>
struct xxxRequest_
{
  typedef xxxRequest_<ContainerAllocator> Type;

  xxxRequest_()
    : num1(0)
    , num2(0)  {
    }
  xxxRequest_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int32_t _num1_type;
  _num1_type num1;

   typedef int32_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::ros2_2::xxxRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros2_2::xxxRequest_<ContainerAllocator> const> ConstPtr;

}; // struct xxxRequest_

typedef ::ros2_2::xxxRequest_<std::allocator<void> > xxxRequest;

typedef boost::shared_ptr< ::ros2_2::xxxRequest > xxxRequestPtr;
typedef boost::shared_ptr< ::ros2_2::xxxRequest const> xxxRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros2_2::xxxRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros2_2::xxxRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros2_2::xxxRequest_<ContainerAllocator1> & lhs, const ::ros2_2::xxxRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros2_2::xxxRequest_<ContainerAllocator1> & lhs, const ::ros2_2::xxxRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros2_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros2_2::xxxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros2_2::xxxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros2_2::xxxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros2_2::xxxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros2_2::xxxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros2_2::xxxRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros2_2::xxxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c68f3979e1a90aac7d1c75a1096d1e60";
  }

  static const char* value(const ::ros2_2::xxxRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc68f3979e1a90aacULL;
  static const uint64_t static_value2 = 0x7d1c75a1096d1e60ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros2_2::xxxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros2_2/xxxRequest";
  }

  static const char* value(const ::ros2_2::xxxRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros2_2::xxxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 客户端请求时发送的两个数字\n"
"int32 num1\n"
"int32 num2\n"
;
  }

  static const char* value(const ::ros2_2::xxxRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros2_2::xxxRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xxxRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros2_2::xxxRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros2_2::xxxRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "num1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS2_2_MESSAGE_XXXREQUEST_H
